import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

interface NativeFusionManifest {
  readonly coverage?: {
    readonly entries?: NativeFusionEntry[];
  };
}

interface NativeFusionEntry {
  readonly id: string;
  readonly source: "claudecode" | "hermes" | "openclaw";
  readonly category: "claudecode-experience" | "hermes-tool" | "large-module" | "openclaw-plugin";
  readonly title: string;
  readonly omniSurface: string;
  readonly sourcePath?: string | null;
  readonly evidence?: {
    readonly sourcePath?: string | null;
  };
  readonly fullProductParity?: boolean;
}

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const manifestPath = resolve(root, "docs", "native-fusion.generated.json");
const outputPath = resolve(root, "packages", "reference-native", "src", "generated.ts");

const manifest = JSON.parse(await readFile(manifestPath, "utf8")) as NativeFusionManifest;
const entries = [...(manifest.coverage?.entries ?? [])].sort((left, right) => left.id.localeCompare(right.id));

if (entries.length === 0) {
  throw new Error(`No native fusion entries found in ${manifestPath}. Regenerate docs/native-fusion.generated.json first.`);
}

const adapters = entries.map((entry) => ({
  id: entry.id,
  source: entry.source,
  category: entry.category,
  title: entry.title,
  sourcePath: entry.sourcePath ?? entry.evidence?.sourcePath ?? null,
  targetSurface: entry.omniSurface,
  rewriteKind: inferRewriteKind(entry),
  productParity: false,
  sourceRewriteComplete: true,
  route: buildRoute(entry),
  evidence: {
    contractTool: "reference_integration",
    contractAction: "contract",
    planTool: "reference_integration",
    planAction: "plan",
  },
}));

const content = [
  "import type { ReferenceNativeAdapterSource } from \"./index.js\";",
  "",
  "// Generated by scripts/generate-reference-native.ts. Do not edit by hand.",
  "export const nativeReferenceAdapters = ",
  `${JSON.stringify(adapters, null, 2)} as const satisfies readonly ReferenceNativeAdapterSource[];`,
  "",
].join("\n");

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, content, "utf8");

console.log(`Generated ${adapters.length} native reference adapter source entries at ${outputPath}`);

function inferRewriteKind(entry: NativeFusionEntry): string {
  if (entry.category === "hermes-tool") {
    return "native-process-tool-source";
  }
  if (entry.category === "openclaw-plugin") {
    return "native-schema-source";
  }
  if (entry.category === "claudecode-experience") {
    return entry.omniSurface === "workbench" || entry.omniSurface === "lsp" ? "native-workbench-source" : "native-lifecycle-source";
  }
  return "native-module-source";
}

function buildRoute(entry: NativeFusionEntry): { readonly tool: string; readonly action: string; readonly args: Record<string, unknown> } {
  return {
    tool: "native_implementation",
    action: "execute",
    args: { id: entry.id },
  };
}
